name: components_codelab
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.22
  angular2_components:
    path: ../acx
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  intl: ^0.14.0
transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
      Random: 'dart:math'
- dart_to_js_script_rewriter
